name: 'Action to build Mendix Widgets in Lerna monorepo'
description: 'Build all widgets and publish mpks in release'
author: 'Arno Boel'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  author_name:
    description: 'Git Author Name'
    required: false
  identify_widgets_folders:
    description: 'identify_widgets_folders'
    required: false
  release_version:
    description: 'release_version'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
